openapi: 3.0.3
info:
  title: 'Endpoints Documentation'
  description: 'Simple project for generate laravel documentation'
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: 'Get User Data'
      description: "Check that the service is up. If everything is okay, you'll get a 200 OK response.\n\nOtherwise, the request will fail with a 400 error, and a response listing the failed services."
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        400:
          description: 'Service is unhealthy'
          content:
            application/json:
              schema:
                type: object
                example:
                  status: down
                  services:
                    database: up
                    redis: down
                properties:
                  status:
                    type: string
                    example: down
                    description: 'The status of this API (`up` or `down`).'
                  services:
                    type: object
                    example:
                      database: up
                      redis: down
                    description: 'Map of each downstream service and their status (`up` or `down`).'
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: TESTE
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
